#!/usr/bin/env node
/**
 * computeSiteStats.mjs
 * ─────────────────────────────────────────────────────────────────────────────
 * Regenerates src/data/siteStats.ts from the actual archive.
 *
 * These numbers drive the homepage scale strip. They were hand-maintained and
 * had drifted badly (366,921 records vs 422,053 actual; 12 tracked events vs 17;
 * "data from 1992" when the oldest edition on file is Wellington Half 1996).
 * Deriving them means the homepage can't silently misstate the archive again.
 *
 * Run as part of `npm run generate`, AFTER buildAthleteCanon.mjs (it reads the
 * profile shards for the athlete count).
 * From project root:  node scripts/computeSiteStats.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { TRAIL_EVENT_FAMILIES } from '../src/data/trailEvents.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT     = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'public', 'data');
const ATHLETES = path.join(DATA_DIR, 'athletes');
const OUT      = path.join(ROOT, 'src', 'data', 'siteStats.ts');
const RACE_META = path.join(ROOT, 'src', 'data', 'raceMeta.ts');

// ─── Finisher records + earliest edition ─────────────────────────────────────
// Counts every row in the archive. NOTE: this is slightly higher than the canon
// build's row count (422,018), which skips rows whose name can't be normalised
// into a key. "Finisher records" is the archive figure — the records we hold.
let finisherRecords = 0;
let earliestEdition = 9999;
let earliestFile = '';
const resultFiles = fs.readdirSync(DATA_DIR).filter(f => f.startsWith('results-') && f.endsWith('.json'));
for (const f of resultFiles) {
  const yM = f.match(/(\d{4})\.json$/);
  if (yM) {
    const y = parseInt(yM[1], 10);
    if (y < earliestEdition) { earliestEdition = y; earliestFile = f; }
  }
  try {
    const rows = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8'));
    if (Array.isArray(rows)) finisherRecords += rows.length;
  } catch { /* skip unreadable file */ }
}

// ─── Tracked events: race families the site presents as race pages ───────────
// Road families come from RACE_META's slugs (same regex-parse approach
// buildAthleteCanon uses on athleteRegistry.ts); trail families from the config.
const roadSlugs = [...fs.readFileSync(RACE_META, 'utf8').matchAll(/^\s{4}slug: '([^']+)'/gm)].map(m => m[1]);
const trackedEvents = new Set([...roadSlugs, ...TRAIL_EVENT_FAMILIES.map(f => f.familySlug)]).size;

// ─── Athlete profiles: the browsable (multi-race) cohort ─────────────────────
let athleteProfiles = 0;
if (fs.existsSync(ATHLETES)) {
  for (const f of fs.readdirSync(ATHLETES).filter(f => f.endsWith('.json'))) {
    athleteProfiles += Object.keys(JSON.parse(fs.readFileSync(path.join(ATHLETES, f), 'utf8'))).length;
  }
}

// ─── Course records published across the site ────────────────────────────────
// Road: each RaceDistance carrying a men's record (women's is always paired).
// Trail: each course era with a record — contingency-only eras have none by
// design, so they correctly don't count.
const roadRecords = (fs.readFileSync(RACE_META, 'utf8').match(/recordM:/g) ?? []).length;
let trailRecords = 0;
const trailStatsDir = path.join(DATA_DIR, 'trail');
if (fs.existsSync(trailStatsDir)) {
  for (const f of fs.readdirSync(trailStatsDir).filter(f => f.endsWith('-stats.json'))) {
    const s = JSON.parse(fs.readFileSync(path.join(trailStatsDir, f), 'utf8'));
    for (const sub of Object.values(s.subEvents ?? {})) {
      for (const era of sub.eras ?? []) if (era.recordM) trailRecords++;
    }
  }
}
const courseRecords = roadRecords + trailRecords;

// ─── Emit ────────────────────────────────────────────────────────────────────
const banner = `// GENERATED by scripts/computeSiteStats.mjs — do not edit by hand.
// Regenerated on every \`npm run generate\` so the homepage scale strip can never
// drift from the archive again. Change the derivation, not these values.`;

const body = `${banner}
export const SITE_STATS = {
  /** Every row across public/data/results-*.json (${resultFiles.length} files). */
  finisherRecords: ${finisherRecords},
  /** Race families with a race page: road (raceMeta) + trail (trailEvents). */
  trackedEvents: ${trackedEvents},
  /** Athletes with 2+ logged races — the cohort that gets a profile page. */
  athleteProfiles: ${athleteProfiles},
  /** Published course records: road distances + trail course eras. */
  courseRecords: ${courseRecords},
  /** Oldest edition on file (${earliestFile.replace(/^results-|\.json$/g, '')}). */
  earliestEdition: ${earliestEdition},
} as const;
`;

const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
fs.writeFileSync(OUT, body);

console.log('');
console.log('── Site stats ─────────────────────────────────────────────────');
console.log(`   Finisher records : ${finisherRecords.toLocaleString()}   (${resultFiles.length} result files)`);
console.log(`   Tracked events   : ${trackedEvents}   (${roadSlugs.length} road + ${TRAIL_EVENT_FAMILIES.length} trail)`);
console.log(`   Athlete profiles : ${athleteProfiles.toLocaleString()}`);
console.log(`   Course records   : ${courseRecords}   (${roadRecords} road + ${trailRecords} trail eras)`);
console.log(`   Earliest edition : ${earliestEdition}   (${earliestFile})`);
console.log(`   → src/data/siteStats.ts ${prev === body ? '(unchanged)' : '(updated)'}`);
console.log('───────────────────────────────────────────────────────────────');
console.log('');
