// Auto-generated by scripts/generateChangelog.mjs — do not edit by hand.
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_FILE = path.resolve(__dirname, '../src/data/recentlyAdded.ts');

const RACE_NAMES = {
  omaha: 'Omaha Half Marathon',
  coatesville: 'Coatesville Half Marathon',
  kerikeri: 'Kerikeri Half Marathon',
  maraetai: 'Maraetai Half Marathon',
  wellington: 'Wellington Marathon',
  christchurch: 'Christchurch Marathon',
  auckland: 'Auckland Marathon',
  rotorua: 'Rotorua Marathon',
  queenstown: 'Queenstown Marathon',
  hawkes: "Hawke's Bay Marathon",
  waterfront: 'Waterfront Half Marathon',
  devonport: 'Devonport Half Marathon',
};

// Commits matching these patterns are skipped entirely
const SKIP_RE = /fix\(landing\)|fix\(search\)|feat\(search\)|chore:|feat\(landing\)|merge|search index|hero|nav|css|style|deploy/i;

function parseCommit(date, hash, subject) {
  if (SKIP_RE.test(subject)) return null;

  // --- Course record (check before erratum) ---
  if (/course record/i.test(subject)) {
    return { date, tag: 'record', accent: true, em: subject, rest: ' · Course record.' };
  }

  // --- Backfill / historical ---
  if (/backfill|historical/i.test(subject)) {
    return { date, tag: 'backfill', accent: false, em: subject, rest: ' · Historical results indexed.' };
  }

  // --- Race results: feat(slug): add ... race page OR add ... results ---
  // Check this BEFORE athlete profile so "Add X race page" doesn't accidentally match athlete regex
  const featSlugRe = /^feat\((\w[\w-]*)\):/;
  const featSlugMatch = subject.match(featSlugRe);
  if (featSlugMatch) {
    const slug = featSlugMatch[1].toLowerCase();
    const raceName = RACE_NAMES[slug];

    if (raceName) {
      const isResultsCommit =
        /add.*race page/i.test(subject) ||
        /add.*results/i.test(subject);

      if (isResultsCommit) {
        // Try to extract year count
        const yearMatch = subject.match(/(\d+)\s+year/i);
        const rest = yearMatch
          ? ` · ${yearMatch[1]} years of results indexed.`
          : ' · Results indexed.';
        return { date, tag: 'results', accent: false, em: raceName, rest };
      }
    }
    // feat(slug) but not a results commit — skip
    return null;
  }

  // --- Bare "Add X race page" commit (no feat() prefix) ---
  const addRaceRe = /^Add\s+(.+?)\s+race page/i;
  const addRaceMatch = subject.match(addRaceRe);
  if (addRaceMatch) {
    const title = addRaceMatch[1].trim();
    // Try to find a matching race name
    const matched = Object.values(RACE_NAMES).find(
      n => title.toLowerCase().includes(n.toLowerCase()) || n.toLowerCase().includes(title.toLowerCase())
    );
    const em = matched || title;
    return { date, tag: 'results', accent: false, em, rest: ' · Results indexed.' };
  }

  // --- Single athlete profile: "Add <Name> athlete profile" (not "add N new athlete profiles") ---
  // Must be exactly one name (not "9 new" or "Maraetai and Kerikeri appearances to")
  const singleAthleteRe = /^(?:feat\([^)]+\):\s*)?[Aa]dd\s+([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z]+)?)\s+athlete\s+profile/;
  const athleteMatch = subject.match(singleAthleteRe);
  if (athleteMatch) {
    const name = athleteMatch[1].replace(/\s*\(#\d+\)\s*$/, '').trim();
    return { date, tag: 'profile', accent: false, em: name, rest: ' · Athlete profile added.' };
  }

  // --- Erratum / correction (last, since "corrected CSVs" in fix() commits should still be skipped) ---
  // Only fire for commits that look like genuine result corrections, not CSV refreshes
  if (/fix.*result.*correct|correct.*split|erratum/i.test(subject) && !/corrected CSV/i.test(subject)) {
    return { date, tag: 'erratum', accent: false, em: subject, rest: ' · Correction applied.' };
  }

  return null;
}

function main() {
  const raw = execSync(
    'git log --pretty=format:"%ad|%H|%s" --date=format:"%d %b %Y" --no-merges -60',
    { cwd: path.resolve(__dirname, '..'), encoding: 'utf8' }
  ).trim();

  const lines = raw.split('\n').filter(Boolean);
  const entries = [];
  const seen = new Set(); // dedup key: em+tag

  for (const line of lines) {
    const pipeIdx1 = line.indexOf('|');
    const pipeIdx2 = line.indexOf('|', pipeIdx1 + 1);
    if (pipeIdx1 === -1 || pipeIdx2 === -1) continue;

    const date = line.slice(0, pipeIdx1);
    const hash = line.slice(pipeIdx1 + 1, pipeIdx2);
    const subject = line.slice(pipeIdx2 + 1);

    const entry = parseCommit(date, hash, subject);
    if (!entry) continue;

    const key = `${entry.em}|${entry.tag}`;
    if (seen.has(key)) continue;
    seen.add(key);

    entries.push(entry);
    if (entries.length >= 8) break;
  }

  const json = JSON.stringify(entries, null, 2);
  const ts = `// Auto-generated by scripts/generateChangelog.mjs — do not edit by hand.
export interface LedgerEntry {
  date: string;
  em: string;
  rest: string;
  tag: string;
  accent: boolean;
}

export const RECENTLY_ADDED: LedgerEntry[] = ${json};
`;

  writeFileSync(OUT_FILE, ts, 'utf8');
  console.log(`[generateChangelog] wrote ${entries.length} entries to ${OUT_FILE}`);
}

main();
