// GENERATED by scripts/roadToJson.mjs — do not edit by hand.
// Re-run: node scripts/roadToJson.mjs huntly

import type { YearStat } from './logsDataExt';

export const HUNTLY_HALF_YEARS = [2019, 2022, 2023, 2024, 2025, 2026] as const;

export const huntlyHalfStats: YearStat[] = [
  { year: 2019, finishers:  424, avg:  6927, avgMen:  6626, avgWomen:  7814, winnerM:  4249, winnerW:  5152, top10M:  4577, top10W:  5560 },
  { year: 2022, finishers:  178, avg:  7543, avgMen:  7202, avgWomen:  8241, winnerM:  4227, winnerW:  5003, top10M:  4682, top10W:  6172 },
  { year: 2023, finishers:  344, avg:  6821, avgMen:  6704, avgWomen:  7570, winnerM:  4134, winnerW:  4679, top10M:  4556, top10W:  5138 },
  { year: 2024, finishers:  396, avg:  6933, avgMen:  6687, avgWomen:  7799, winnerM:  4091, winnerW:  4662, top10M:  4495, top10W:  5293 },
  { year: 2025, finishers:  410, avg:  8420, avgMen:  8063, avgWomen:  9663, winnerM:  4469, winnerW:  4690, top10M:  4901, top10W:  6187 },
  { year: 2026, finishers:  326, avg:  7505, avgMen:  7311, avgWomen:  8622, winnerM:  5056, winnerW:  4798, top10M:  5299, top10W:  5918 },
];
