// Auto-generated by scripts/generateChangelog.mjs — do not edit by hand.
export interface LedgerEntry {
  date: string;
  em: string;
  rest: string;
  tag: string;
  accent: boolean;
}

export const RECENTLY_ADDED: LedgerEntry[] = [
  {
    "date": "23 May 2026",
    "tag": "profile",
    "accent": false,
    "em": "Amelia Lythe",
    "rest": " · Athlete profile added."
  },
  {
    "date": "23 May 2026",
    "tag": "profile",
    "accent": false,
    "em": "Kylie Brown",
    "rest": " · Athlete profile added."
  },
  {
    "date": "22 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Wellington Marathon",
    "rest": " · Results indexed."
  },
  {
    "date": "20 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Kerikeri Half Marathon",
    "rest": " · 14 years of results indexed."
  },
  {
    "date": "20 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Maraetai Half Marathon",
    "rest": " · 8 years of results indexed."
  },
  {
    "date": "20 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Omaha Half Marathon",
    "rest": " · 21 years of results indexed."
  },
  {
    "date": "20 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Coatesville Half Marathon",
    "rest": " · 16 years of results indexed."
  },
  {
    "date": "13 May 2026",
    "tag": "results",
    "accent": false,
    "em": "Waterfront Half Marathon",
    "rest": " · Results indexed."
  }
];
