// GENERATED by scripts/roadToJson.mjs — do not edit by hand.
// Re-run: node scripts/roadToJson.mjs saintclair

import type { YearStat } from './logsDataExt';

export const SAINTCLAIR_HALF_YEARS = [2008, 2009, 2010, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025, 2026] as const;

export const saintClairHalfStats: YearStat[] = [
  { year: 2008, finishers:  223, avg:  7365, avgMen:  6921, avgWomen:  7776, winnerM:  4935, winnerW:  5494, top10M:  5355, top10W:  6210 },
  { year: 2009, finishers:  414, avg:  7351, avgMen:  6931, avgWomen:  7727, winnerM:  4440, winnerW:  5376, top10M:  5229, top10W:  5863 },
  { year: 2010, finishers:  580, avg:  7450, avgMen:  7000, avgWomen:  7917, winnerM:  4691, winnerW:  5297, top10M:  5245, top10W:  5858 },
  { year: 2012, finishers:  908, avg:  7341, avgMen:  6858, avgWomen:  7813, winnerM:  4655, winnerW:  5411, top10M:  4989, top10W:  5590 },
  { year: 2013, finishers: 1123, avg:  7446, avgMen:  6756, avgWomen:  7899, winnerM:  4427, winnerW:  5368, top10M:  4807, top10W:  5551 },
  { year: 2014, finishers:  157, avg:  6216, avgMen:  5869, avgWomen:  6681, winnerM:  4636, winnerW:  5281, top10M:  4964, top10W:  5694 },
  { year: 2015, finishers: 1199, avg:  7776, avgMen:  7187, avgWomen:  8272, winnerM:  4672, winnerW:  5483, top10M:  5020, top10W:  5714 },
  { year: 2016, finishers: 1197, avg:  7803, avgMen:  7192, avgWomen:  8292, winnerM:  4803, winnerW:  5253, top10M:  5123, top10W:  5684 },
  { year: 2017, finishers: 1195, avg:  7742, avgMen:  7147, avgWomen:  8291, winnerM:  4810, winnerW:  5038, top10M:  5112, top10W:  5673 },
  { year: 2018, finishers: 1233, avg:  7740, avgMen:  7307, avgWomen:  8250, winnerM:  4779, winnerW:  5146, top10M:  5172, top10W:  5649 },
  { year: 2019, finishers:  660, avg:  7001, avgMen:  6598, avgWomen:  7110, winnerM:  4595, winnerW:  4962, top10M:  5084, top10W:  5464 },
  { year: 2021, finishers:  678, avg:  7583, avgMen:  7013, avgWomen:  8188, winnerM:  4790, winnerW:  5463, top10M:  5118, top10W:  5688 },
  { year: 2022, finishers:  209, avg:  7307, avgMen:     0, avgWomen:     0, winnerM:     0, winnerW:     0, top10M:     0, top10W:     0 },
  { year: 2023, finishers:  467, avg:  7181, avgMen:  6708, avgWomen:  7793, winnerM:  4396, winnerW:  5162, top10M:  4928, top10W:  5443 },
  { year: 2024, finishers:  545, avg:  7109, avgMen:  6651, avgWomen:  7742, winnerM:  4454, winnerW:  4828, top10M:  4794, top10W:  5374 },
  { year: 2025, finishers:  568, avg:  7366, avgMen:  6954, avgWomen:  7855, winnerM:  4571, winnerW:  5067, top10M:  5041, top10W:  5545 },
  { year: 2026, finishers:  479, avg:  7723, avgMen:  7162, avgWomen:  8192, winnerM:  4937, winnerW:  5492, top10M:  5397, top10W:  5880 },
];

export const SAINTCLAIR_12K_YEARS = [2021, 2022, 2023, 2024, 2025, 2026] as const;

export const saintClair12kStats: YearStat[] = [
  { year: 2021, finishers:  434, avg:  5065, avgMen:  4706, avgWomen:  5236, winnerM:  3028, winnerW:  3056, top10M:  3448, top10W:  3339 },
  { year: 2022, finishers:  205, avg:  5069, avgMen:     0, avgWomen:     0, winnerM:     0, winnerW:     0, top10M:     0, top10W:     0 },
  { year: 2023, finishers:  287, avg:  4861, avgMen:  4429, avgWomen:  5248, winnerM:  2772, winnerW:  2909, top10M:  3314, top10W:  3331 },
  { year: 2024, finishers:  389, avg:  4788, avgMen:  4527, avgWomen:  5139, winnerM:  3025, winnerW:  3039, top10M:  3267, top10W:  3408 },
  { year: 2025, finishers:  401, avg:  4911, avgMen:  4711, avgWomen:  5304, winnerM:  3064, winnerW:  3060, top10M:  3303, top10W:  3530 },
  { year: 2026, finishers:  375, avg:  5091, avgMen:  4765, avgWomen:  5623, winnerM:  2898, winnerW:  3310, top10M:  3148, top10W:  3698 },
];
