// GENERATED by scripts/computeSiteStats.mjs — do not edit by hand.
// Regenerated on every `npm run generate` so the homepage scale strip can never
// drift from the archive again. Change the derivation, not these values.
export const SITE_STATS = {
  /** Every row across public/data/results-*.json (423 files). */
  finisherRecords: 425774,
  /** Race families with a race page: road (raceMeta) + trail (trailEvents). */
  trackedEvents: 17,
  /** Athletes with 2+ logged races — the cohort that gets a profile page. */
  athleteProfiles: 74756,
  /** Published course records: road distances + trail course eras. */
  courseRecords: 43,
  /** Oldest edition on file (wellington-half-1996). */
  earliestEdition: 1996,
} as const;
