// GENERATED by scripts/roadToJson.mjs — do not edit by hand.
// Re-run: node scripts/roadToJson.mjs taupo

import type { YearStat } from './logsDataExt';

export const TAUPO_MAR_YEARS = [2019, 2020, 2021, 2022, 2023, 2024, 2025] as const;

export const taupoMarStats: YearStat[] = [
  { year: 2019, finishers:  173, avg: 15624, avgMen: 15665, avgWomen: 17060, winnerM: 10606, winnerW: 11455, top10M: 11199, top10W: 13017 },
  { year: 2020, finishers:  164, avg: 15753, avgMen: 15255, avgWomen: 18686, winnerM:  9610, winnerW: 12046, top10M: 10673, top10W: 13914 },
  { year: 2021, finishers:  239, avg: 15674, avgMen: 15626, avgWomen: 17820, winnerM:  9570, winnerW: 11174, top10M: 10422, top10W: 12874 },
  { year: 2022, finishers:  175, avg: 15265, avgMen: 15314, avgWomen: 17876, winnerM:  9976, winnerW: 11815, top10M: 10359, top10W: 13009 },
  { year: 2023, finishers:  274, avg: 15705, avgMen: 15569, avgWomen: 17883, winnerM:  9364, winnerW: 11000, top10M: 10335, top10W: 11714 },
  { year: 2024, finishers:  383, avg: 15004, avgMen: 15187, avgWomen: 17562, winnerM:  9423, winnerW: 10972, top10M: 10182, top10W: 12431 },
  { year: 2025, finishers:  518, avg: 15043, avgMen: 14664, avgWomen: 17303, winnerM:  9241, winnerW: 10732, top10M:  9878, top10W: 12000 },
];

export const TAUPO_HALF_YEARS = [2019, 2020, 2021, 2022, 2023, 2024, 2025] as const;

export const taupoHalfStats: YearStat[] = [
  { year: 2019, finishers:  860, avg:  7375, avgMen:  7099, avgWomen:  8396, winnerM:  4243, winnerW:  4965, top10M:  4526, top10W:  5480 },
  { year: 2020, finishers:  476, avg:  7426, avgMen:  7169, avgWomen:  8435, winnerM:  4128, winnerW:  4921, top10M:  4532, top10W:  5512 },
  { year: 2021, finishers: 1010, avg:  7350, avgMen:  7130, avgWomen:  8387, winnerM:  3998, winnerW:  4597, top10M:  4527, top10W:  5184 },
  { year: 2022, finishers:  668, avg:  7241, avgMen:  7084, avgWomen:  8184, winnerM:  4219, winnerW:  5179, top10M:  4564, top10W:  5616 },
  { year: 2023, finishers:  925, avg:  7262, avgMen:  7056, avgWomen:  8345, winnerM:  4487, winnerW:  4875, top10M:  4682, top10W:  5557 },
  { year: 2024, finishers: 1470, avg:  7558, avgMen:  7172, avgWomen:  8349, winnerM:  4003, winnerW:  4892, top10M:  4474, top10W:  5406 },
  { year: 2025, finishers: 1817, avg:  7507, avgMen:  7177, avgWomen:  8317, winnerM:  4022, winnerW:  5274, top10M:  4334, top10W:  5507 },
];

export const TAUPO_10K_YEARS = [2020, 2021, 2022, 2023, 2024, 2025] as const;

export const taupo10kStats: YearStat[] = [
  { year: 2020, finishers:  186, avg:  3790, avgMen:  3727, avgWomen:  4060, winnerM:  2284, winnerW:  2510, top10M:  2592, top10W:  2907 },
  { year: 2021, finishers:  582, avg:  4049, avgMen:  3812, avgWomen:  4363, winnerM:  2059, winnerW:  2391, top10M:  2363, top10W:  2732 },
  { year: 2022, finishers:  401, avg:  3826, avgMen:  3587, avgWomen:  4175, winnerM:  2163, winnerW:  2482, top10M:  2265, top10W:  2794 },
  { year: 2023, finishers:  438, avg:  3824, avgMen:  3728, avgWomen:  4157, winnerM:  1889, winnerW:  2245, top10M:  2181, top10W:  2490 },
  { year: 2024, finishers:  935, avg:  4005, avgMen:  3829, avgWomen:  4318, winnerM:  2054, winnerW:  2378, top10M:  2298, top10W:  2635 },
  { year: 2025, finishers: 1177, avg:  4141, avgMen:  3877, avgWomen:  4461, winnerM:  2084, winnerW:  2398, top10M:  2186, top10W:  2733 },
];

export const TAUPO_5K_YEARS = [2020, 2021, 2022, 2023, 2024, 2025] as const;

export const taupo5kStats: YearStat[] = [
  { year: 2020, finishers:   58, avg:  1861, avgMen:  1855, avgWomen:  1970, winnerM:  1027, winnerW:  1579, top10M:  1465, top10W:  1686 },
  { year: 2021, finishers:  166, avg:  2010, avgMen:  2013, avgWomen:  2225, winnerM:  1210, winnerW:  1249, top10M:  1356, top10W:  1505 },
  { year: 2022, finishers:  160, avg:  2062, avgMen:  1964, avgWomen:  2207, winnerM:  1178, winnerW:  1168, top10M:  1318, top10W:  1391 },
  { year: 2023, finishers:  202, avg:  2086, avgMen:  2032, avgWomen:  2156, winnerM:   977, winnerW:  1309, top10M:  1198, top10W:  1446 },
  { year: 2024, finishers:  377, avg:  2059, avgMen:  2119, avgWomen:  2331, winnerM:  1028, winnerW:  1191, top10M:  1110, top10W:  1275 },
  { year: 2025, finishers:  422, avg:  1961, avgMen:  1997, avgWomen:  2123, winnerM:  1026, winnerW:  1036, top10M:  1175, top10W:  1247 },
];
