// GENERATED by scripts/roadToJson.mjs — do not edit by hand.
// Re-run: node scripts/roadToJson.mjs whanganui

import type { YearStat } from './logsDataExt';

export const WHANGANUI_MAR_YEARS = [2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025] as const;

export const whanganuiMarStats: YearStat[] = [
  { year: 2017, finishers:   46, avg: 16424, avgMen: 15129, avgWomen: 18524, winnerM: 10152, winnerW: 14873, top10M: 11719, top10W: 16248 },
  { year: 2018, finishers:   66, avg: 16410, avgMen: 16361, avgWomen: 17577, winnerM: 10763, winnerW: 11997, top10M: 11862, top10W: 14519 },
  { year: 2019, finishers:   75, avg: 16740, avgMen: 15943, avgWomen: 19203, winnerM: 10080, winnerW: 14262, top10M: 10915, top10W: 15954 },
  { year: 2020, finishers:   69, avg: 16274, avgMen: 15661, avgWomen: 19368, winnerM:  9417, winnerW: 13459, top10M: 10925, top10W: 14778 },
  { year: 2022, finishers:   56, avg: 15926, avgMen: 15966, avgWomen: 19045, winnerM:  8846, winnerW: 13505, top10M: 10993, top10W: 15300 },
  { year: 2023, finishers:   66, avg: 15426, avgMen: 15359, avgWomen: 18527, winnerM:  9517, winnerW: 12169, top10M: 11067, top10W: 14597 },
  { year: 2024, finishers:   83, avg: 15417, avgMen: 14432, avgWomen: 18051, winnerM:  9855, winnerW: 12049, top10M: 10314, top10W: 14315 },
  { year: 2025, finishers:  102, avg: 14674, avgMen: 14537, avgWomen: 17928, winnerM: 10090, winnerW: 12564, top10M: 11164, top10W: 14149 },
];

export const WHANGANUI_HALF_YEARS = [2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025] as const;

export const whanganuiHalfStats: YearStat[] = [
  { year: 2017, finishers:  112, avg:  7257, avgMen:  6862, avgWomen:  8034, winnerM:  4579, winnerW:  5655, top10M:  5248, top10W:  6159 },
  { year: 2018, finishers:  125, avg:  7341, avgMen:  7038, avgWomen:  7989, winnerM:  4834, winnerW:  5817, top10M:  5134, top10W:  6323 },
  { year: 2019, finishers:  120, avg:  7236, avgMen:  6923, avgWomen:  8166, winnerM:  4730, winnerW:  6138, top10M:  5067, top10W:  6692 },
  { year: 2020, finishers:  108, avg:  6781, avgMen:  6717, avgWomen:  7808, winnerM:  4448, winnerW:  5500, top10M:  5098, top10W:  6073 },
  { year: 2022, finishers:  124, avg:  7215, avgMen:  7148, avgWomen:  8070, winnerM:  4755, winnerW:  5374, top10M:  5354, top10W:  6518 },
  { year: 2023, finishers:  180, avg:  7212, avgMen:  6865, avgWomen:  8059, winnerM:  4668, winnerW:  5275, top10M:  5094, top10W:  5908 },
  { year: 2024, finishers:  228, avg:  7345, avgMen:  7137, avgWomen:  8093, winnerM:  4206, winnerW:  5214, top10M:  5276, top10W:  6121 },
  { year: 2025, finishers:  251, avg:  7559, avgMen:  7245, avgWomen:  8385, winnerM:  4196, winnerW:  4925, top10M:  5109, top10W:  5763 },
];

export const WHANGANUI_QUARTER_YEARS = [2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025] as const;

export const whanganuiQuarterStats: YearStat[] = [
  { year: 2017, finishers:   80, avg:  3925, avgMen:  3567, avgWomen:  4406, winnerM:  2663, winnerW:  2726, top10M:  3017, top10W:  3204 },
  { year: 2018, finishers:  110, avg:  3965, avgMen:  3507, avgWomen:  4353, winnerM:  2435, winnerW:  2543, top10M:  2644, top10W:  3052 },
  { year: 2019, finishers:  101, avg:  3989, avgMen:  3713, avgWomen:  4365, winnerM:  2323, winnerW:  2854, top10M:  2855, top10W:  3375 },
  { year: 2020, finishers:  103, avg:  3856, avgMen:  3666, avgWomen:  4168, winnerM:  2552, winnerW:  2914, top10M:  2719, top10W:  3248 },
  { year: 2022, finishers:  136, avg:  3992, avgMen:  3741, avgWomen:  4384, winnerM:  2737, winnerW:  3079, top10M:  2893, top10W:  3354 },
  { year: 2023, finishers:  151, avg:  3856, avgMen:  3612, avgWomen:  4354, winnerM:  2214, winnerW:  2651, top10M:  2663, top10W:  2947 },
  { year: 2024, finishers:  214, avg:  4000, avgMen:  3770, avgWomen:  4326, winnerM:  2442, winnerW:  2319, top10M:  2679, top10W:  2991 },
  { year: 2025, finishers:  248, avg:  4056, avgMen:  3687, avgWomen:  4353, winnerM:  2381, winnerW:  2574, top10M:  2498, top10W:  3097 },
];

export const WHANGANUI_5K_YEARS = [2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025] as const;

export const whanganui5kStats: YearStat[] = [
  { year: 2017, finishers:   56, avg:  1872, avgMen:  1675, avgWomen:  2054, winnerM:  1219, winnerW:  1556, top10M:  1326, top10W:  1641 },
  { year: 2018, finishers:   67, avg:  1862, avgMen:  1778, avgWomen:  2168, winnerM:  1212, winnerW:  1455, top10M:  1377, top10W:  1643 },
  { year: 2019, finishers:   78, avg:  1853, avgMen:  1868, avgWomen:  2044, winnerM:  1072, winnerW:  1247, top10M:  1357, top10W:  1458 },
  { year: 2020, finishers:   76, avg:  1863, avgMen:  1808, avgWomen:  2203, winnerM:  1277, winnerW:  1337, top10M:  1472, top10W:  1650 },
  { year: 2022, finishers:   65, avg:  2117, avgMen:  2070, avgWomen:  2183, winnerM:  1364, winnerW:  1463, top10M:  1640, top10W:  1717 },
  { year: 2023, finishers:   82, avg:  2049, avgMen:  2000, avgWomen:  2337, winnerM:  1218, winnerW:  1426, top10M:  1374, top10W:  1776 },
  { year: 2024, finishers:  145, avg:  1973, avgMen:  1937, avgWomen:  2207, winnerM:  1075, winnerW:  1323, top10M:  1235, top10W:  1530 },
  { year: 2025, finishers:  198, avg:  2063, avgMen:  1985, avgWomen:  2331, winnerM:  1056, winnerW:  1135, top10M:  1307, top10W:  1504 },
];
